# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of replicas for the deployment
replicaCount: 1

# Container image configuration
image:
  repository: your-dockerhub-username/finel_project-web  # עדכני עם שם המשתמש שלך ב-DockerHub
  tag: latest
  pullPolicy: IfNotPresent

# Image pull secrets (use if the image is private)
imagePullSecrets: []
# Example for private image:
# imagePullSecrets:
#   - name: my-registry-secret

# Overrides for the chart name
nameOverride: ""
fullnameOverride: ""

# Service account settings
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security settings for the pod
podSecurityContext: {}
securityContext: {}

# Service configuration
service:
  type: NodePort  # אם את משתמשת ב-GKE/EKS/AKS שימי LoadBalancer
  port: 5000

# Ingress configuration (if needed)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource requests and limits (optional)
resources: {}

# Liveness and Readiness Probes
livenessProbe:
  httpGet:
    path: /
    port: 5000
readinessProbe:
  httpGet:
    path: /
    port: 5000

# Autoscaling settings (enable if needed)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Volumes (if needed)
volumes: []
volumeMounts: []

# Node selector, tolerations, and affinity settings
nodeSelector: {}
tolerations: []
affinity: {}
