apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  DB_USERNAME: bXl1c2Vy  # כאן שימי את הערך המקודד
  DB_PASSWORD: cGFzc3dvcmQ=  # שימי פה סיסמה מקודדת (תצטרכי להמיר אותה ל-Base64)
