name: CD Pipeline

on:
  push:
    tags:
      - "v*.*.*"  # רץ רק כאשר יוצרים גרסה חדשה (v1.0.0)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .
          docker tag my-app:latest my-dockerhub-user/my-app:${{ github.ref_name }}

      - name: Push to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push my-dockerhub-user/my-app:${{ github.ref_name }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
