name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest ./tests  

  build:
    name: Build Docker Image for Minikube
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          minikube start --driver=docker

      - name: Build Docker Image Inside Minikube
        run: |
          eval $(minikube docker-env)  # מחבר את Docker ל-Minikube
          docker build -t finel_project-web:latest .

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Minikube
        run: |
          minikube start --driver=docker

      - name: Deploy with Helm to Minikube
        run: |
          helm upgrade --install finel-project ./helm-chart -f helm-chart/values.yaml
