name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest ./tests  

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/finel_project-web:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/finel_project-web:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Cloud Provider & Connect to Kubernetes
        run: |
          # התחברות ל-AWS EKS
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws eks --region us-east-1 update-kubeconfig --name my-cluster

          # אם את משתמשת ב-GCP GKE
          # gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          # gcloud container clusters get-credentials my-cluster --zone us-central1-a --project my-gcp-project

          # אם את משתמשת ב-Azure AKS
          # az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          # az aks get-credentials --resource-group my-resource-group --name my-cluster

          kubectl get nodes
          kubectl get pods -A

      - name: Deploy with Helm
        run: |
          helm upgrade --install finel-project ./helm-chart -f values.yaml
