name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest ./tests  

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/finel_project-web:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/finel_project-web:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Fix Missing Packages)
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack

          # התקנת cri-tools (תיקון ל-Ubuntu 24.04)
          CRI_TOOLS_VERSION="1.28.0"
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v$CRI_TOOLS_VERSION/crictl-v$CRI_TOOLS_VERSION-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf crictl-v$CRI_TOOLS_VERSION-linux-amd64.tar.gz
          rm crictl-v$CRI_TOOLS_VERSION-linux-amd64.tar.gz
          crictl --version  # בדיקה שהותקן

          # התקנת containernetworking-plugins (תיקון לבעיית רשת ב-Minikube)
          CNI_VERSION="1.3.0"
          sudo mkdir -p /opt/cni/bin
          curl -LO https://github.com/containernetworking/plugins/releases/download/v$CNI_VERSION/cni-plugins-linux-amd64-v$CNI_VERSION.tgz
          sudo tar -C /opt/cni/bin -xzf cni-plugins-linux-amd64-v$CNI_VERSION.tgz
          rm cni-plugins-linux-amd64-v$CNI_VERSION.tgz
          ls -lah /opt/cni/bin  # בדיקה שהותקן

          # התקנת cri-dockerd (חובה לדוקר)
          sudo apt-get install -y git wget curl
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          mkdir -p bin
          go build -o bin/cri-dockerd ./cmd/cri-dockerd
          sudo install -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
          sudo ln -s /usr/local/bin/cri-dockerd /usr/bin/cri-dockerd
          cd ..
          rm -rf cri-dockerd
          cri-dockerd --version  # בדיקה שהותקן

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          sudo systemctl start cri-docker.service
          sudo minikube start --driver=none --container-runtime=docker
          sudo nohup minikube tunnel > /dev/null 2>&1 &

      - name: Ensure Minikube is Running
        run: |
          minikube status || minikube start --driver=none --container-runtime=docker
          minikube addons enable default-storageclass
          minikube addons enable storage-provisioner

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          minikube update-context
          export KUBECONFIG=$HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Verify Kubernetes Connection
        run: |
          minikube status
          kubectl config view
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -A

      - name: Deploy with Helm
        run: |
          helm upgrade --install finel-project ./helm-chart -f values.yaml
