name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # מריץ את ה-Workflow רק כשיש שינוי ב-main
  workflow_dispatch:  # אפשרות להריץ ידנית דרך GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes Context
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify Kubernetes Connection
        run: kubectl cluster-info

      - name: Deploy with Helm
        run: |
          helm upgrade --install finel-project ./helm-chart -f values.yaml
